services:
  app:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  worker:
    build: .
    command: python -m celery -A app.tasks.worker worker --loglevel=info
    depends_on:
      - app
      - redis
    env_file: .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
